/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v2/exchange-rates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a list of current exchange rates
         * @description Get current exchange rates. Default base currency is USD but it can be defined as any supported currency (see Currencies endpoint). Returned rates will define the exchange rate for one unit of the base currency
         */
        get: {
            parameters: {
                query?: {
                    currency?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The currency response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["ExchangeRateResponse"];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @example {
         *       "data": {
         *         "currency": "BTC",
         *         "rates": {
         *           "AED": "36.73",
         *           "AFN": "589.50",
         *           "ALL": "1258.82",
         *           "AMD": "4769.49",
         *           "ANG": "17.88",
         *           "AOA": "1102.76",
         *           "ARS": "90.37",
         *           "AUD": "12.93",
         *           "AWG": "17.93",
         *           "AZN": "10.48",
         *           "BAM": "17.38"
         *         }
         *       }
         *     } */
        ExchangeRateResponse: {
            currency?: string;
            rates?: {
                [key: string]: string;
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
