/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/conversions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Convert a currency amount from one currency to another
         * @description Converts funds from from currency to to currency. Funds are converted on the from account in the profile_id profile.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description The conversion response */
            requestBody?: {
                content: {
                    "application/json": {
                        data?: components["schemas"]["ConversionRequest"];
                    };
                };
            };
            responses: {
                /** @description The conversion response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["ConversionResponse"];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ConversionRequest: {
            /** @description Profile ID */
            profile_id?: string;
            /** @description Currency the amount is in */
            from: string;
            /** @description Currency to convert to */
            to: string;
            /** @description Amount to convert */
            amount: number;
        };
        /** @example {
         *       "id": "c5aaf125-d99e-41fe-82ea-ad068038b278",
         *       "amount": "11.00000000",
         *       "from_account_id": "5dcc143c-fb96-4f72-aebf-a165e3d29b53",
         *       "to_account_id": "6100247f-90fc-4335-ac17-d99839f0c909",
         *       "from": "USDC",
         *       "to": "USD",
         *       "fee_amount": "0.0000000000000000"
         *     } */
        ConversionResponse: {
            id: string;
            amount: string;
            from_account_id: string;
            to_account_id: string;
            fee_amount: string;
            from?: string;
            to?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
